version: "3.9"
services:
  web:
    build: .
    container_name: "python_polls"
    entrypoint: /app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/src/
      - polls_log_volume:/var/log
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env
  db:
    image: "postgres:14"
    container_name: "postgres_polls"
    restart: always
    volumes:
      - polls_db_volume:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polls_db

volumes:
  polls_db_volume: {}
  polls_log_volume: {}

networks:
  backend: {}